name: "Check Security Features"

on:
  workflow_run:
    workflows: ["Dependabot", "CodeQL Analysis", "Secrets Scanning"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Dependabot
        id: check_dependabot
        run: echo "::set-output name=dependabot_enabled::$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/topics | jq '.names' | grep -q '\"dependabot\"' && echo 'true' || echo 'false')"

      - name: Check CodeQL Analysis
        id: check_codeql_analysis
        run: echo "::set-output name=codeql_analysis_enabled::$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/code-scanning/config | jq '.status' | grep -q 'enabled' && echo 'true' || echo 'false')"

      - name: Check Secrets Scanning
        id: check_secrets_scanning
        run: echo "::set-output name=secrets_scanning_enabled::$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/secret-scanning/config | jq '.status' | grep -q 'enabled' && echo 'true' || echo 'false')"

      - name: Check Secrets Push Protection
        id: check_secrets_push_protection
        run: echo "::set-output name=secrets_push_protection_enabled::$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/secret-scanning/alerts | jq '.alerts[0].enabled' && echo 'true' || echo 'false')"

  fail-if-not-enabled:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any security feature is not enabled
        run: |
          if [ "${{ needs.check.outputs.dependabot_enabled }}" != "true" ] || \
             [ "${{ needs.check.outputs.codeql_analysis_enabled }}" != "true" ] || \
             [ "${{ needs.check.outputs.secrets_scanning_enabled }}" != "true" ] || \
             [ "${{ needs.check.outputs.secrets_push_protection_enabled }}" != "true" ]; then
            echo "One or more security features are not enabled. Please enable all of the following: Dependabot, CodeQL Analysis, Secrets Scanning, Secrets Push Protection."
            exit 1
          fi
