name: "Check Security Features"

on:
  workflow_run:
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Dependabot
        id: check_dependabot
        run: |
          DEPENDABOT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/dependabot/alerts)
          if [[ "$DEPENDABOT" == *"Not Found"* ]]; then
            echo "Dependabot is not enabled"
            exit 1
          fi

      - name: Check Code Scanning
        id: check_code_scanning
        run: |
          CODE_SCANNING=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts)
          if [[ "$CODE_SCANNING" == *"Not Found"* ]]; then
            echo "Code Scanning is not enabled"
            exit 1
          fi

      - name: Check Secrets Scanning
        id: check_secrets_scanning
        run: |
          SECRETS_SCANNING=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/secrets)
          if [[ "$SECRETS_SCANNING" == *"Not Found"* ]]; then
            echo "Secrets Scanning is not enabled"
            exit 1
          fi